"use client";
import {AnimatePresence,motion} from "framer-motion";
import {ArrowLeft,ArrowRight,Check,Clock3,LockKeyhole,MessageCircle,Package,Plane,Ship,Sparkles,Truck} from "lucide-react";
import {useMemo,useState} from "react";
const routes=[{id:"pen-sabah",label:"Peninsular → Sabah",detail:"Kota Kinabalu, Labuan & statewide delivery"},{id:"pen-sarawak",label:"Peninsular → Sarawak",detail:"Kuching, Bintulu & statewide delivery"},{id:"east-pen",label:"East Malaysia → Peninsular",detail:"Reverse logistics and return movements"}];
const cargo=[{id:"household",label:"Household Moving",detail:"Furniture, appliances & personal effects",icon:Truck},{id:"commercial",label:"Commercial Goods",detail:"Stock, machinery & business cargo",icon:Package},{id:"medical",label:"Medical / Specialized",detail:"Sensitive, high-value or specialist equipment",icon:Sparkles},{id:"ecommerce",label:"Bulk E-Commerce",detail:"Consolidated seller inventory & fulfilment stock",icon:MessageCircle}];
export default function InstantQuote(){
 const[step,setStep]=useState(1),[route,setRoute]=useState(routes[0].id),[cargoType,setCargoType]=useState(cargo[0].id),[quantity,setQuantity]=useState(300),[unit,setUnit]=useState<"kg"|"cbm">("kg"),[form,setForm]=useState({name:"",email:"",whatsapp:""}),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
 const selectedRoute=routes.find(x=>x.id===route)!,selectedCargo=cargo.find(x=>x.id===cargoType)!;
 const estimate=useMemo(()=>{const weight=unit==="kg"?quantity:quantity*167;return{air:Math.round(Math.max(1850,1250+weight*7.8)/50)*50,sea:Math.round(Math.max(980,720+weight*2.65)/50)*50,weight}},[quantity,unit]);
 const lock=async()=>{setError("");if(!form.name||!form.email||!form.whatsapp){setError("Enter your name, business email and WhatsApp number to continue.");return}setSaving(true);try{const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,route:selectedRoute.label,cargoType:selectedCargo.label,quantity,quantityUnit:unit})});if(!r.ok)throw 0;setSaved(true);setStep(5)}catch{setError("We could not lock the rate right now. Please check your details and try again.")}finally{setSaving(false)}};
 return <section id="quote" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="mb-10 max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-blue-700"><Sparkles size={13}/> Instant quote matrix</div><h2 className="text-4xl font-black tracking-[-.04em] sm:text-5xl">Know the lane before you call.</h2><p className="mt-4 text-lg leading-8 text-slate-600">A guided estimate built around your route, cargo profile and urgency. Final pricing is confirmed against the actual shipment details.</p></div>
 <div className="glass overflow-hidden rounded-[32px]"><div className="flex items-center justify-between border-b border-slate-200 px-6 py-5 sm:px-8"><div className="flex gap-2">{[1,2,3,4,5].map(i=><div key={i} className={`h-1.5 w-10 rounded-full ${i<=step?"bg-blue-600":"bg-slate-200"}`}/>)}</div><span className="text-xs font-bold uppercase tracking-widest text-slate-400">Step {step} / 5</span></div>
 <div className="min-h-[500px] p-6 sm:p-10"><AnimatePresence mode="wait">
 {step===1&&<motion.div key="r" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}}><Head e="01 / Route" t="Where is the cargo moving?"/><div className="mt-8 grid gap-4 md:grid-cols-3">{routes.map(x=><Choice key={x.id} active={route===x.id} onClick={()=>setRoute(x.id)}><div className="mb-5 flex justify-between"><span className="rounded-xl bg-blue-50 p-3 text-blue-700"><Truck size={21}/></span>{route===x.id&&<Check className="text-blue-600" size={20}/>}</div><h3 className="font-bold">{x.label}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{x.detail}</p></Choice>)}</div></motion.div>}
 {step===2&&<motion.div key="c" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}}><Head e="02 / Cargo profile" t="What are you moving?"/><div className="mt-8 grid gap-4 sm:grid-cols-2">{cargo.map(x=>{const I=x.icon;return <Choice key={x.id} active={cargoType===x.id} onClick={()=>setCargoType(x.id)}><div className="mb-5 flex justify-between"><span className="rounded-xl bg-slate-100 p-3 text-slate-800"><I size={21}/></span>{cargoType===x.id&&<Check className="text-blue-600" size={20}/>}</div><h3 className="font-bold">{x.label}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{x.detail}</p></Choice>})}</div></motion.div>}
 {step===3&&<motion.div key="v" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}}><Head e="03 / Shipment size" t="Give us the shipment scale."/><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_300px]"><div><div className="mb-8 flex gap-2 rounded-2xl bg-slate-100 p-1">{(["kg","cbm"] as const).map(x=><button key={x} onClick={()=>{setUnit(x);setQuantity(x==="kg"?300:5)}} className={`flex-1 rounded-xl px-4 py-3 text-sm font-bold ${unit===x?"bg-white text-blue-700 shadow-sm":"text-slate-500"}`}>{x==="kg"?"Weight (KG)":"Volume (CBM)"}</button>)}</div><div className="rounded-3xl bg-slate-50 p-7"><div className="flex items-end justify-between"><span className="text-sm font-semibold text-slate-500">Estimated shipment</span><span className="text-5xl font-black">{quantity.toLocaleString()}<small className="ml-2 text-base text-slate-400">{unit.toUpperCase()}</small></span></div><input className="mt-10 w-full" type="range" min={unit==="kg"?50:1} max={unit==="kg"?3000:30} step={unit==="kg"?50:1} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/><div className="mt-3 flex justify-between text-xs font-semibold text-slate-400"><span>{unit==="kg"?"50 KG":"1 CBM"}</span><span>{unit==="kg"?"3,000 KG":"30 CBM"}</span></div></div></div><div className="rounded-3xl bg-[#071a35] p-7 text-white"><div className="text-xs font-bold uppercase tracking-[.18em] text-blue-300">Routing context</div><p className="mt-5 text-xl font-bold">{selectedRoute.label}</p><p className="mt-2 text-sm leading-6 text-slate-300">{selectedCargo.label}</p><div className="mt-8 border-t border-white/10 pt-6"><p className="text-xs text-slate-400">Planning weight</p><p className="mt-1 text-2xl font-black">{Math.round(estimate.weight).toLocaleString()} KG</p></div></div></div></motion.div>}
 {step===4&&<motion.div key="l" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}} className="mx-auto max-w-2xl"><Head e="04 / Secure the estimate" t="Where should we send your rate?"/><p className="mt-3 text-slate-500">We use these details to save your shipment brief and make the next conversation faster.</p><div className="mt-8 space-y-4"><Field l="Name" v={form.name} set={v=>setForm({...form,name:v})} p="Your name"/><Field l="Corporate email" v={form.email} set={v=>setForm({...form,email:v})} p="name@company.com" type="email"/><Field l="WhatsApp number" v={form.whatsapp} set={v=>setForm({...form,whatsapp:v})} p="+60 12 345 6789"/></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button disabled={saving} onClick={lock} className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl bg-blue-600 px-5 py-4 font-bold text-white shadow-xl shadow-blue-600/20 disabled:opacity-60"><LockKeyhole size={18}/>{saving?"Securing your shipment brief…":"Lock in current promo rate"}</button><div className="mt-5 flex justify-center gap-5 text-xs font-semibold text-slate-400"><span className="inline-flex items-center gap-1"><LockKeyhole size={13}/> Secure submission</span><span>•</span><span>No obligation to book</span></div></motion.div>}
 {step===5&&<motion.div key="q" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="flex flex-wrap items-end justify-between gap-4"><Head e="05 / Planning view" t="Your route, side by side." />{saved&&<span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-4 py-2 text-xs font-bold text-emerald-700"><Check size={14}/> Shipment brief saved</span>}</div><div className="mt-8 grid gap-5 lg:grid-cols-2"><Quote kind="air" price={estimate.air}/><Quote kind="sea" price={estimate.sea}/></div><div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50 p-5 text-sm leading-6 text-blue-900"><strong>Planning note:</strong> Estimates are directional. Final rates depend on dimensions, actual chargeable weight, cargo characteristics, pickup/delivery points and current carrier conditions.</div></motion.div>}
 </AnimatePresence></div>
 {step<4&&<div className="flex justify-end border-t border-slate-200 px-6 py-5 sm:px-10"><button onClick={()=>setStep(s=>Math.min(5,s+1))} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white hover:bg-blue-700">Continue <ArrowRight size={16}/></button></div>}
 {step===4&&<div className="border-t border-slate-200 px-6 py-5 sm:px-10"><button onClick={()=>setStep(3)} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Back to shipment size</button></div>}
 {step===5&&<div className="border-t border-slate-200 px-6 py-5 sm:px-10"><button onClick={()=>setStep(1)} className="text-sm font-bold text-slate-500">Start another estimate</button></div>}
 </div></section>
}
function Head({e,t}:{e:string;t:string}){return <><div className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">{e}</div><h3 className="mt-3 text-3xl font-black tracking-[-.03em] sm:text-4xl">{t}</h3></>}
function Choice({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`w-full rounded-3xl border p-6 text-left transition ${active?"border-blue-500 bg-blue-50/60 shadow-lg shadow-blue-100":"border-slate-200 bg-white hover:border-slate-300"}`}>{children}</button>}
function Field({l,v,set,p,type="text"}:{l:string;v:string;set:(v:string)=>void;p:string;type?:string}){return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{l}</span><input required type={type} value={v} onChange={e=>set(e.target.value)} placeholder={p} className="w-full rounded-2xl border border-slate-200 px-4 py-4 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></label>}
function Quote({kind,price}:{kind:"air"|"sea";price:number}){const air=kind==="air";return <div className={`rounded-[28px] border p-7 ${air?"border-blue-200 bg-gradient-to-br from-blue-50 to-white":"border-slate-200 bg-white"}`}><div className="flex justify-between"><span className={`rounded-xl p-3 ${air?"bg-blue-600":"bg-slate-900"} text-white`}>{air?<Plane size={21}/>:<Ship size={21}/>}</span><span className="text-xs font-bold uppercase tracking-widest text-slate-400">{air?"Priority":"Consolidated"}</span></div><h4 className="mt-7 text-2xl font-black">{air?"Air Freight":"Sea Freight"}</h4><div className="mt-2 flex items-baseline gap-2"><span className="text-4xl font-black">RM {price.toLocaleString()}</span><span className="text-sm text-slate-400">planning estimate</span></div><div className="mt-6 flex items-center gap-2 text-sm font-bold"><Clock3 size={17}/>{air?"3–4 days":"2–3 weeks"}</div><div className="mt-5 h-2 rounded-full bg-slate-200"><motion.div initial={{width:0}} animate={{width:air?"86%":"64%"}} transition={{duration:.9}} className={`h-full rounded-full ${air?"bg-blue-600":"bg-slate-700"}`}/></div></div>}
